# Generated by Django 5.0.1 on 2024-02-12 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cart",
            managers=[],
        ),
    ]
